# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301
#   force = false
#   query = {path = ":path"}
#   conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

# Prismatic

[[redirects]]
  from = "/downloads/prismatic/download-prismatic"
  to = "/prismatic/download"
  status = 301
  force = true
  query = { path = ":path" }

# [[redirects]]
#   from = "/downloads/prismatic"
#   to = "/prismatic"
#   status = 301
#   force = true
#   query = { path = ":path" }
